# Generated by Django 4.0.1 on 2022-01-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('breed', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=300)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
