# Generated by Django 4.0.1 on 2022-01-13 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finch',
            old_name='breed',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='finch',
            old_name='description',
            new_name='ocupation',
        ),
    ]
