# Generated by Django 4.0.1 on 2022-01-13 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_breed_finch_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finch',
            old_name='ocupation',
            new_name='occupation',
        ),
    ]
